[programs.localnet]
synapse = "eCv677gAYX6ptLtJrPv9Rj8C4eGA4c9ecswRT5QJbeG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "../dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
